[print_schema]
file = "/home/taha/Code/EcommerceRS/src/adapters/postgres/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/taha/Code/EcommerceRS/src/adapters/postgres/migrations"
