version = "0.0.1"

[server]
host = "127.0.0.1"
port = 8000
allowed_origins = ["*"]

[postgres]
url = "postgresql://admin:admin@localhost:5432/default"

[redis]
url = "redis://127.0.0.1:6379/0"

[jwt]
secret = "secret"