[package]
name = "restapi"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
ecommercers = { path = "../../", version = "*" }

[[bin]]
name = "ecommercers-restapi"
path = "./src/server.rs"
